import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeModeScript } from "flowbite-react";
import { PropsWithChildren } from "react";
import SideBar from "./common/SideBar";
import AdminNavBar from "./common/AdminNavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MyProfil Dashboard",
  description: "Generated by MyProfil Dashboard",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeModeScript />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-dvh w-dvw overflow-hidden">
          <SideBar />
          <div className="flex-1 bg-gray-100 h-dvh overflow-y-auto">
            <AdminNavBar />
            <div className="p-4">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
